### ISSUE TITLE
docker_info throws error on Windows

### ISSUE THREAD

**Issue by josh-barker** [test-kitchen/kitchen-dokken#156]
On Windows 10, the `default_config :docker_info` causes an error because it tries to connect to the default `'unix:///var/run/docker.sock'` connection. 

However, it would be ideal if I can just run `test kitchen` commands

- https://github.com/someara/kitchen-dokken/blob/master/lib/kitchen/helpers.rb#L119
- https://github.com/swipely/docker-api/blob/master/lib/docker.rb#L113
- https://github.com/swipely/docker-api/blob/master/lib/docker.rb#L39

## Gem Versions
- test kitchen: 1.21.2
- kitchen-dokken: 2.6.7

## Workaround

One work around is to set `$env:DOCKER_HOST = "tcp://127.0.0.1:2375"`

## Stack Trace

```
-----> Starting Kitchen (v1.21.2)
Traceback (most recent call last):
        64: from C:/opscode/chefdk/bin/kitchen:284:in `<main>'
        63: from C:/opscode/chefdk/bin/kitchen:284:in `load'
        62: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/bin/kitchen:13:in `<top (required)>'
        61: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
        60: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/bin/kitchen:13:in `block in <top (required)>'
        59: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        58: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        57: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        56: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        55: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
        54: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/cli.rb:52:in `perform'
        53: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command/action.rb:34:in `call'
        52: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
        51: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command/action.rb:35:in `block in call'
        50: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command.rb:142:in `parse_subcommand'
        49: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/command.rb:112:in `filtered_instances'
        48: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/config.rb:117:in `instances'
        47: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/config.rb:141:in `build_instances'
        46: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/config.rb:141:in `with_index'
        45: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/config.rb:141:in `map'
        44: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/config.rb:142:in `block in build_instances'
        43: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/config.rb:247:in `new_instance'
        42: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/config.rb:234:in `new_driver'
        41: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.21.2/lib/kitchen/driver.rb:38:in `for_plugin'
        40: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        39: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        38: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-dokken-2.6.7/lib/kitchen/driver/dokken.rb:30:in `<top (required)>'
        37: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-dokken-2.6.7/lib/kitchen/driver/dokken.rb:31:in `<module:Kitchen>'
        36: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-dokken-2.6.7/lib/kitchen/driver/dokken.rb:35:in `<module:Driver>'
        35: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-dokken-2.6.7/lib/kitchen/driver/dokken.rb:45:in `<class:Dokken>'
        34: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-dokken-2.6.7/lib/kitchen/helpers.rb:119:in `docker_info'
        33: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/docker-api-1.34.2/lib/docker.rb:114:in `info'
        32: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/docker-api-1.34.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
        31: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/docker-api-1.34.2/lib/docker/connection.rb:40:in `request'
        30: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:225:in `request'
        29: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:283:in `rescue in request'
        28: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:11:in `error_call'
        27: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:11:in `error_call'
        26: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:11:in `error_call'
        25: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/idempotent.rb:33:in `error_call'
        24: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:225:in `request'
        23: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:283:in `rescue in request'
        22: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:11:in `error_call'
        21: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:11:in `error_call'
        20: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:11:in `error_call'
        19: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/idempotent.rb:33:in `error_call'
        18: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:225:in `request'
        17: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:283:in `rescue in request'
        16: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:11:in `error_call'
        15: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:11:in `error_call'
        14: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:11:in `error_call'
        13: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/idempotent.rb:33:in `error_call'
        12: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:260:in `request'
        11: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
        10: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
         9: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
         8: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
         7: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
         6: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/mock.rb:48:in `request_call'
         5: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
         4: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:111:in `request_call'
         3: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:427:in `socket'
         2: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:427:in `new'
         1: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/socket.rb:30:in `initialize'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/unix_socket.rb:12:in `connect': undefined method `sockaddr_un' for Socket:Class (Excon::Error::Socket)
Did you mean?  sockaddr_in (NoMethodError)
```

**Comment by tas50** [comment]
Not that it fixes this, but #158 will make the error more useful.
