### ISSUE TITLE
Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by AlexanderYW** [test-kitchen/kitchen-dokken#196]
## :ghost: Brief Description

Trying to do `kitchen create`, machine complains of missing dockerfile
Cannot locate the dockerfile either when looking in the folder with windows explorer

## Version

kitchen-dokken version 2.10.0 & 2.9.0

## Environment
AzureVM - Windows 10 Enterprise N - Version 1803 - OS Build 17134.1550
ChefDK version 4.9.7-1 - 64bit
Docker version 2.3.0.3 (45519)

kitchen.yml
```
---
driver:
  name: dokken
  chef_version: latest
  #privileged: true
  #volumes: [ '/var/lib/docker' ]
  env: [CHEF_LICENSE="accept-silent"]

driver_config:
  hostname: automate.local

transport:
  name: dokken

provisioner:
  name: dokken
  chef_log_level: debug

verifier:
  name: inspec

platforms:
- name: centos
  driver:
    image: dokken/centos-7
    privileged: true
    pull_platform_image: true
  provisioner:
    chef_binary: /bin/true
```

## Scenario

I cannot do `kitchen create` without getting the following error
```
I, [2020-07-16T15:18:04.334496 #14940]  INFO -- Kitchen: -----> Starting Test Kitchen (v2.5.2)
I, [2020-07-16T15:18:15.648164 #14940]  INFO -- Kitchen: -----> Creating <default-centos>...
E, [2020-07-16T15:18:20.993692 #14940] ERROR -- Kitchen: ------Exception-------
E, [2020-07-16T15:18:20.994016 #14940] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2020-07-16T15:18:20.994194 #14940] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Cannot locate specified Dockerfile: Dockerfile
] on default-centos
E, [2020-07-16T15:18:20.994419 #14940] ERROR -- Kitchen: ----------------------
E, [2020-07-16T15:18:20.994595 #14940] ERROR -- Kitchen: ------Backtrace-------
E, [2020-07-16T15:18:20.994769 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/command.rb:184:in `report_errors'
E, [2020-07-16T15:18:20.995042 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/command.rb:175:in `run_action'
E, [2020-07-16T15:18:20.995338 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/command/action.rb:36:in `block in call'
E, [2020-07-16T15:18:20.995557 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
E, [2020-07-16T15:18:20.995729 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/command/action.rb:34:in `call'
E, [2020-07-16T15:18:20.995899 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/cli.rb:52:in `perform'
E, [2020-07-16T15:18:20.997538 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
E, [2020-07-16T15:18:20.997721 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
E, [2020-07-16T15:18:20.998029 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
E, [2020-07-16T15:18:20.998218 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
E, [2020-07-16T15:18:20.998530 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
E, [2020-07-16T15:18:21.000094 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/bin/kitchen:13:in `block in <top (required)>'
E, [2020-07-16T15:18:21.000275 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2020-07-16T15:18:21.000477 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/bin/kitchen:13:in `<top (required)>'
E, [2020-07-16T15:18:21.000774 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/bin/kitchen:368:in `load'
E, [2020-07-16T15:18:21.000952 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/bin/kitchen:368:in `<main>'
E, [2020-07-16T15:18:21.001123 #14940] ERROR -- Kitchen: ----End Backtrace-----
E, [2020-07-16T15:18:21.001373 #14940] ERROR -- Kitchen: -Composite Exception--
E, [2020-07-16T15:18:21.002593 #14940] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2020-07-16T15:18:21.002812 #14940] ERROR -- Kitchen: Message: Failed to complete #create action: [Cannot locate specified Dockerfile: Dockerfile
] on default-centos
E, [2020-07-16T15:18:21.003099 #14940] ERROR -- Kitchen: ----------------------
E, [2020-07-16T15:18:21.003255 #14940] ERROR -- Kitchen: ------Backtrace-------
E, [2020-07-16T15:18:21.003501 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/docker-api-1.34.2/lib/docker/connection.rb:50:in `rescue in request'
E, [2020-07-16T15:18:21.003680 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/docker-api-1.34.2/lib/docker/connection.rb:37:in `request'
E, [2020-07-16T15:18:21.003838 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/docker-api-1.34.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
E, [2020-07-16T15:18:21.003990 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/docker-api-1.34.2/lib/docker/image.rb:274:in `build_from_tar'
E, [2020-07-16T15:18:21.004151 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/docker-api-1.34.2/lib/docker/image.rb:293:in `build_from_dir'
E, [2020-07-16T15:18:21.004297 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/kitchen-dokken-2.9.0/lib/kitchen/helpers.rb:97:in `create_data_image'
E, [2020-07-16T15:18:21.004560 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/kitchen-dokken-2.9.0/lib/kitchen/driver/dokken.rb:362:in `make_data_image'
E, [2020-07-16T15:18:21.004780 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/kitchen-dokken-2.9.0/lib/kitchen/driver/dokken.rb:81:in `create'
E, [2020-07-16T15:18:21.004994 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:485:in `public_send'
E, [2020-07-16T15:18:21.005212 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:485:in `block in perform_action'
E, [2020-07-16T15:18:21.005561 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:552:in `synchronize_or_call'
E, [2020-07-16T15:18:21.005782 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:514:in `block in action'
E, [2020-07-16T15:18:21.005966 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
E, [2020-07-16T15:18:21.006117 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:513:in `action'
E, [2020-07-16T15:18:21.006268 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:485:in `perform_action'
E, [2020-07-16T15:18:21.006479 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:394:in `create_action'
E, [2020-07-16T15:18:21.006631 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2020-07-16T15:18:21.006779 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2020-07-16T15:18:21.006928 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2020-07-16T15:18:21.007081 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:380:in `each'
E, [2020-07-16T15:18:21.007238 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2020-07-16T15:18:21.007492 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:129:in `create'
E, [2020-07-16T15:18:21.007653 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/command.rb:198:in `public_send'
E, [2020-07-16T15:18:21.007792 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/command.rb:198:in `run_action_in_thread'
E, [2020-07-16T15:18:21.007929 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2020-07-16T15:18:21.008064 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2020-07-16T15:18:21.008205 #14940] ERROR -- Kitchen: ----End Backtrace-----
E, [2020-07-16T15:18:21.008339 #14940] ERROR -- Kitchen: ---Nested Exception---
E, [2020-07-16T15:18:21.008579 #14940] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2020-07-16T15:18:21.008763 #14940] ERROR -- Kitchen: Message: Failed to complete #create action: [Cannot locate specified Dockerfile: Dockerfile
]
E, [2020-07-16T15:18:21.008899 #14940] ERROR -- Kitchen: ----------------------
E, [2020-07-16T15:18:21.009047 #14940] ERROR -- Kitchen: ------Backtrace-------
E, [2020-07-16T15:18:21.009210 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/docker-api-1.34.2/lib/docker/connection.rb:50:in `rescue in request'
E, [2020-07-16T15:18:21.009384 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/docker-api-1.34.2/lib/docker/connection.rb:37:in `request'
E, [2020-07-16T15:18:21.009618 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/docker-api-1.34.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
E, [2020-07-16T15:18:21.009783 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/docker-api-1.34.2/lib/docker/image.rb:274:in `build_from_tar'
E, [2020-07-16T15:18:21.009932 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/docker-api-1.34.2/lib/docker/image.rb:293:in `build_from_dir'
E, [2020-07-16T15:18:21.010100 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/kitchen-dokken-2.9.0/lib/kitchen/helpers.rb:97:in `create_data_image'
E, [2020-07-16T15:18:21.010238 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/kitchen-dokken-2.9.0/lib/kitchen/driver/dokken.rb:362:in `make_data_image'
E, [2020-07-16T15:18:21.010377 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/kitchen-dokken-2.9.0/lib/kitchen/driver/dokken.rb:81:in `create'
E, [2020-07-16T15:18:21.010849 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:485:in `public_send'
E, [2020-07-16T15:18:21.010998 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:485:in `block in perform_action'
E, [2020-07-16T15:18:21.011137 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:552:in `synchronize_or_call'
E, [2020-07-16T15:18:21.011290 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:514:in `block in action'
E, [2020-07-16T15:18:21.011503 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
E, [2020-07-16T15:18:21.011701 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:513:in `action'
E, [2020-07-16T15:18:21.011847 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:485:in `perform_action'
E, [2020-07-16T15:18:21.011986 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:394:in `create_action'
E, [2020-07-16T15:18:21.012125 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2020-07-16T15:18:21.012264 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2020-07-16T15:18:21.012433 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2020-07-16T15:18:21.012612 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:380:in `each'
E, [2020-07-16T15:18:21.012753 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2020-07-16T15:18:21.012894 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:129:in `create'
E, [2020-07-16T15:18:21.013032 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/command.rb:198:in `public_send'
E, [2020-07-16T15:18:21.013169 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/command.rb:198:in `run_action_in_thread'
E, [2020-07-16T15:18:21.013308 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.5.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2020-07-16T15:18:21.013543 #14940] ERROR -- Kitchen: C:/java_devenv/programs/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2020-07-16T15:18:21.013689 #14940] ERROR -- Kitchen: ----End Backtrace-----

```

## Expected Result

Being able do `kitchen create` without any errors

## Actual Result

Look at "Scenario" section

**Comment by marcparadise** [comment]
This is not reproduceable on current versions of Kitchen. I'm closing this issue, but  AlexanderYW if you are still encountering this on the current Kitchen/kitchen-dokken, please re-open this issue with updated details.
