### ISSUE TITLE
connect_write timeout reached

### ISSUE THREAD

**Issue by Radik2** [test-kitchen/kitchen-dokken#267]
Hello team,

I cloned the repository and tried to execute kitchen create or kitchen list but I get following error:

 kitchen create
C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker/connection.rb:91:in `rescue in request': connect_write timeout reached (Docker::Error::TimeoutError)
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker/connection.rb:44:in `request'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker/connection.rb:109:in `block (2 levels) in <class:Connection>'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker/connection.rb:114:in `info'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker.rb:114:in `info'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/kitchen-dokken-2.17.0/lib/kitchen/helpers.rb:122:in `docker_info'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/kitchen-dokken-2.17.0/lib/kitchen/driver/dokken.rb:46:in `<class:Dokken>'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/kitchen-dokken-2.17.0/lib/kitchen/driver/dokken.rb:35:in `<module:Driver>'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/kitchen-dokken-2.17.0/lib/kitchen/driver/dokken.rb:31:in `<module:Kitchen>'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/kitchen-dokken-2.17.0/lib/kitchen/driver/dokken.rb:30:in `<top (required)>'
        from <internal:C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/plugin.rb:35:in `load'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/driver.rb:37:in `for_plugin'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:235:in `new_driver'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:250:in `new_instance'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:143:in `block in build_instances'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:142:in `map'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:142:in `with_index'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:142:in `build_instances'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:116:in `instances'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:109:in `filtered_instances'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:139:in `parse_subcommand'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command/list.rb:29:in `call'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:52:in `perform'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:120:in `list'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `block in <top (required)>'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/errors.rb:183:in `with_friendly_errors'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `<top (required)>'
        from C:/opscode/chef-workstation/bin/kitchen:401:in `load'
        from C:/opscode/chef-workstation/bin/kitchen:401:in `<main>'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/excon-0.92.2/lib/excon/socket.rb:285:in `select_with_timeout': connect_write timeout reached (Excon::Error::Timeout)

## Version

chef --version
Chef Workstation version: 22.4.861
Chef Infra Client version: 17.10.0
Chef InSpec version: 4.56.19
Chef CLI version: 5.6.1
Chef Habitat version: 1.6.420
Test Kitchen version: 3.2.2
Cookstyle version: 7.32.1

ruby -v
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]

kitchen --version
Test Kitchen version 3.2.2

## Environment

Windows 10 Enterprise

## Scenario

To run "kitchen create" as per example

## Steps to Reproduce

1.git clone https://github.com/test-kitchen/kitchen-dokken.git
2.cd to kitchen-dokken
3. kitchen create

## Expected Result

As per example "kitchen create" should run successfully 

## Actual Result

 kitchen create
C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker/connection.rb:91:in `rescue in request': connect_write timeout reached (Docker::Error::TimeoutError)
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker/connection.rb:44:in `request'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker/connection.rb:109:in `block (2 levels) in <class:Connection>'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker/connection.rb:114:in `info'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker.rb:114:in `info'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/kitchen-dokken-2.17.0/lib/kitchen/helpers.rb:122:in `docker_info'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/kitchen-dokken-2.17.0/lib/kitchen/driver/dokken.rb:46:in `<class:Dokken>'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/kitchen-dokken-2.17.0/lib/kitchen/driver/dokken.rb:35:in `<module:Driver>'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/kitchen-dokken-2.17.0/lib/kitchen/driver/dokken.rb:31:in `<module:Kitchen>'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/kitchen-dokken-2.17.0/lib/kitchen/driver/dokken.rb:30:in `<top (required)>'
        from <internal:C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/plugin.rb:35:in `load'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/driver.rb:37:in `for_plugin'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:235:in `new_driver'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:250:in `new_instance'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:143:in `block in build_instances'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:142:in `map'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:142:in `with_index'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:142:in `build_instances'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:116:in `instances'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:109:in `filtered_instances'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:139:in `parse_subcommand'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command/list.rb:29:in `call'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:52:in `perform'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:120:in `list'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `block in <top (required)>'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/errors.rb:183:in `with_friendly_errors'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `<top (required)>'
        from C:/opscode/chef-workstation/bin/kitchen:401:in `load'
        from C:/opscode/chef-workstation/bin/kitchen:401:in `<main>'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/excon-0.92.2/lib/excon/socket.rb:285:in `select_with_timeout': connect_write timeout reached (Excon::Error::Timeout)

## :heavy_plus_sign: Additional context

am i missing something ?

**Comment by Radik2** [comment]
The problem was that "Expose daemon on tcp://localhost:2375 without TLS" option was not enabled in Docker Desktop settings .Issue is fixed.
